const RAW='https://raw.githubusercontent.com/thedrowned925/marvelrivalsodium/main/';
const nf=new Intl.NumberFormat('tr-TR');
let state={data:null,filter:'all',search:'',sort:'progress-desc',cache:new Map(),detail:null};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const pct=n=>Number(n||0).toLocaleString('tr-TR',{maximumFractionDigits:2});
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function enhancePage(){
  const nav=$('.nav-links');if(nav&&!nav.querySelector('[href="#guide"]'))nav.insertAdjacentHTML('afterbegin','<a href="#guide">Nasıl Okunur?</a>');
  const lead=$('.hero-lead');if(lead)lead.textContent='Marvel Rivals kahramanları Türkçe konuşuyor. Kayıttan oyuna, dublaj projemizin her aşamasını takip et.';
  const desc=['Excel’de ayrı çalışma sayfası bulunan ve takip sistemine dahil edilen karakter sayısı.','Tüm karakter sayfalarındaki gerçek replik satırlarının toplamı. Boş şablon satırları sayılmaz.','Kayıt, kontrol veya oyun entegrasyonu aşamasına geçmiş repliklerin toplamı.','Karakter Bazlı sayfasında bir seslendirmen atanmış karakterlerin toplamı.'];
  $$('.stat-card p').forEach((e,i)=>{if(desc[i])e.textContent=desc[i]});
  const pipe=$('#pipeline');if(pipe&&!$('#guide'))pipe.insertAdjacentHTML('beforebegin',`<section class="guide shell" id="guide"><div class="section-heading reveal visible"><div><span class="kicker">// TRACKER GUIDE</span><h2>BU PANELİ <em>NASIL OKURSUN?</em></h2></div><p>Yüzdelerin ne ifade ettiğini ve karakter detaylarında hangi verileri göreceğini burada açıklıyoruz.</p></div><div class="guide-grid"><article class="guide-card glass"><span>01</span><h3>İşlenmiş ne demek?</h3><p>Bir replik “Kayıt Alındı”, “Kontrol Edildi” veya “Oyuna Eklendi” aşamasına geçtiğinde işlenmiş kabul edilir. Bekleyen replikler ilerleme yüzdesine dahil edilmez.</p></article><article class="guide-card glass"><span>02</span><h3>Yüzde nasıl hesaplanır?</h3><p><b>(Kayıt + Kontrol + Oyuna Eklendi) / Toplam replik × 100</b>. Karakter ve proje yüzdeleri aynı mantıkla hesaplanır.</p></article><article class="guide-card glass"><span>03</span><h3>Karaktere basınca?</h3><p>Karakterin Excel sekmesindeki tüm satırlar açılır: sıra, WAV, WEM ID, Internal Name, İngilizce, Türkçe, durum, seslendiren, tarih ve not.</p></article></div><div class="formula-strip"><span>GENEL İLERLEME</span><b>(Kayıt + Kontrol + Oyuna Eklendi) ÷ Tüm Replikler</b><strong id="qualityCompletion">—</strong><small>Kontrol edilmiş + oyuna eklenmiş oranı</small></div></section>`);
  const keys=['waiting','recorded','checked','added'];$$('.pipe-card p').forEach((e,i)=>{if(keys[i]&&!e.querySelector('[data-pct]'))e.insertAdjacentHTML('beforeend',` · <b data-pct="${keys[i]}">%0</b>`)});
  const cp=$('#characters .section-heading p');if(cp)cp.textContent='Kahramanını seç. Türkçe sesini, kayıt ilerlemesini ve tüm repliklerini keşfet.';
}

async function json(url){
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);
  try{const r=await fetch(`${url}${url.includes('?')?'&':'?'}v=${Date.now()}`,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error(r.status);return await r.json();}finally{clearTimeout(timer)}
}
let loadPending=false;
async function load(refresh=false){
  if(loadPending)return;loadPending=true;setSync('syncing');
  try{
    // Render the packaged snapshot immediately, then refresh from the live workbook data.
    if(!state.data){try{state.data=await json('./data/data.json');render(false);setSync('snapshot')}catch{}}
    const next=await json(RAW+'data/data.json');
    if(!next?.stats||!Array.isArray(next.characters))throw Error('Invalid summary');
    const changed=!state.data||next.dataRevision!==state.data.dataRevision||JSON.stringify(next.characters)!==JSON.stringify(state.data.characters);
    state.data=next;
    if(changed){state.cache.clear();render(refresh)}
    $('#sourceUpdate').textContent='Son veri güncellemesi: '+date(next.generatedAt);
    setSync('online');
  }catch(error){
    setSync(state.data?'snapshot':'error');
    if(!state.data){$('#emptyState').hidden=false;$('#emptyState').textContent='Veriler yüklenemedi. Bağlantı yeniden kurulduğunda tekrar denenecek.';}
  }finally{loadPending=false}
}
function setSync(mode){const p=$('#syncPill'),t=$('#syncText');if(!p||!t)return;p.dataset.mode=mode;t.textContent=({online:'CANLI VERİ',syncing:'GÜNCELLENİYOR',snapshot:'KAYITLI VERİ',error:'BAĞLANTI HATASI'})[mode];const legend=$('.legend');if(legend)legend.innerHTML='<i></i> '+(mode==='online'?'Canlı Excel verisi':mode==='syncing'?'Güncellik kontrol ediliyor':'Son kayıtlı veriler');}
function date(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Istanbul'})}
function num(el,to,d=650){const a=performance.now(),from=Number((el.textContent||'0').replace(/\D/g,''))||0;(function f(n){const p=clamp((n-a)/d,0,1),q=1-(1-p)**3;el.textContent=nf.format(Math.round(from+(to-from)*q));if(p<1)requestAnimationFrame(f)})(a)}
function render(refresh){const d=state.data,s=d.stats;$$('[data-stat]').forEach(e=>num(e,s[e.dataset.stat]||0,refresh?300:800));$('#heroProgress').textContent=pct(s.progress)+'%';$('#heroWorked').textContent=`${nf.format(s.worked)} / ${nf.format(s.totalLines)} satır işlendi`;$('#progressOrbit').style.setProperty('--p',clamp(s.progress,0,100));$('#sourceUpdate').textContent=d.generatedAt?'Canlı veri üretildi: '+date(d.generatedAt):(d.sourceWorkbookUpdatedText||'Canlı kaynak bağlı');$('#footerSync').textContent=d.generatedAt?date(d.generatedAt):'LIVE';['waiting','recorded','checked','added'].forEach(k=>{const q=s.totalLines?s[k]/s.totalLines*100:0,b=$(`[data-bar="${k}"]`),pe=$(`[data-pct="${k}"]`);if(b)b.style.width=Math.max(q,k!=='waiting'&&s[k]?0.5:0)+'%';if(pe)pe.textContent='%'+pct(q)});const qc=$('#qualityCompletion');if(qc)qc.textContent='%'+pct(s.totalLines?(s.checked+s.added)/s.totalLines*100:0);ticker();characters();Dossier.update(d)}
function ticker(){const d=state.data,hot=[...d.characters].filter(x=>x.progress>0).sort((a,b)=>b.progress-a.progress).slice(0,6),p=['ODIUM // LIVE TRACKER','MARVEL RIVALS TÜRKÇE DUBLAJ',`${nf.format(d.stats.totalLines)} TOPLAM SATIR`,...hot.map(x=>`${x.name.toUpperCase()} %${pct(x.progress)}`)],h=p.map(x=>`<span>${esc(x)}</span><b>✦</b>`).join('');$('#tickerTrack').innerHTML=h+h}
function label(s){return s==='Baslamadi'?'Başlamadı':s==='Tamamlandi'?'Tamamlandı':s}
function color(s){return s==='Tamamlandi'?'#f6df43':s==='Devam Ediyor'?'#70d9e6':'#a8b6c8'}
function filtered(){const q=state.search.trim().toLocaleLowerCase('tr-TR'),a=state.data.characters.filter(c=>(state.filter==='all'||c.status===state.filter)&&(!q||`${c.name} ${c.voiceActor||''}`.toLocaleLowerCase('tr-TR').includes(q))),[k,dir]=state.sort.split('-');a.sort((x,y)=>{let v=k==='name'?x.name.localeCompare(y.name,'tr'):(x[k]||0)-(y[k]||0);return dir==='desc'?-v:v});return a}
function characters(){if(!state.data)return;const a=filtered(),g=$('#characterGrid');$('#resultCount').textContent=a.length+' karakter';$('#emptyState').hidden=!!a.length;g.innerHTML=a.map((c,i)=>`<article class="char-card tilt-card" data-name="${esc(c.name)}" style="--status-color:${color(c.status)}" tabindex="0" role="button" aria-label="${esc(c.name)} replik ve seslendirme detayları"><span class="card-open-icon" aria-hidden="true">↗</span>${CharacterArt.cardMarkup(c.name,i)}<span class="char-number">${String(i+1).padStart(2,'0')}</span><div class="char-body"><div class="char-head"><div><div class="char-name">${esc(c.name)}</div><div class="status-badge"><i></i>${label(c.status)}</div></div></div><div class="char-progress-row"><span>${nf.format(c.worked??c.recorded+c.checked+c.added)} / ${nf.format(c.total)} işlendi</span><strong>%${pct(c.progress)}</strong></div><div class="char-bar"><i style="width:${clamp(c.progress,0,100)}%"></i></div><div class="char-mini"><span>Bekliyor<b>${nf.format(c.waiting)}</b></span><span>Kayıt<b>${nf.format(c.recorded)}</b></span><span>Kontrol<b>${nf.format(c.checked)}</b></span><span>Oyunda<b>${nf.format(c.added)}</b></span></div><div class="char-meta"><span>SESLENDİREN<br><b>${esc(c.voiceActor||'Atanmadı')}</b></span><span>TOPLAM<br><b>${nf.format(c.total)} SATIR</b></span></div></div></article>`).join('');tilt();$$('.char-card').forEach(e=>{CharacterArt.mount(e);const f=()=>openDetail(e.dataset.name);e.onclick=f;e.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();f()}}});Dossier.decorateCards()}
function slug(v){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
async function detailData(c){
 if(state.cache.has(c.name))return state.cache.get(c.name);
 const path=c.detailPath||`data/characters/${slug(c.name)}.json`;let local;
 try{local=await json('./'+path);if(local.dataRevision&&local.dataRevision===state.data.dataRevision){state.cache.set(c.name,local);return local}}catch{}
 let data;try{data=await json(RAW+path)}catch(error){if(!local)throw error;data=local}
 state.cache.set(c.name,data);return data;
}
async function openDetail(name){const c=state.data.characters.find(x=>x.name===name),m=$('#characterModal');if(!c)return;state.detail={c,d:null,q:'',st:'all',page:1,size:25};$('#modalContent').innerHTML=`<div class="vault loading"><span class="modal-kicker">// CHARACTER DATA VAULT</span><h3>${esc(c.name)}</h3><p>${nf.format(c.total)} satırlık Excel verisi yükleniyor…</p><div class="skeleton"><i></i><i></i><i></i><i></i></div></div>`;if(!m.open)m.showModal();document.body.classList.add('modal-open');const request=state.detail;try{const data=await detailData(c);if(state.detail!==request||!m.open)return;request.d=data;detail()}catch(e){if(state.detail!==request||!m.open)return;$('#modalContent').innerHTML=`<div class="vault error"><span class="modal-kicker">// DATA ERROR</span><h3>${esc(c.name)}</h3><p>Özet verisi mevcut; satır bazlı dosya GitHub senkronizasyonundan sonra otomatik oluşacak.</p></div>`}}
function tile(t,v,s=''){return`<div><small>${t}</small><b>${nf.format(Number(v||0))}</b>${s?`<span>${s}</span>`:''}</div>`}
function detail(){const {c,d}=state.detail,s=d.summary||c,total=s.total||0,worked=s.worked??s.recorded+s.checked+s.added;$('#modalContent').innerHTML=`<div class="vault">${Dossier.stage(c,s,true,d)}<section class="all-lines"><div class="vault-title"><div><span>// FULL SOURCE DATABASE</span><h4>TÜM REPLİK VERİLERİ</h4></div><small id="lineCount">—</small></div><p class="help">Sıra, WAV dosya adı, WEM ID, Internal Name, İngilizce replik, Türkçe çeviri, durum, seslendiren, tarih ve not alanlarının tamamı aşağıdadır. Arama tüm alanlarda çalışır.</p><div class="line-controls"><input id="lineSearch" aria-label="Repliklerde ara" type="search" placeholder="Replik, WAV, WEM ID, çeviri, not ara…"><select id="lineStatus" aria-label="Replik durumu"><option value="all">Tüm durumlar</option><option value="Bekliyor">Bekliyor</option><option value="Kayit Alindi">Kayıt Alındı</option><option value="Kontrol Edildi">Kontrol Edildi</option><option value="Oyuna Eklendi">Oyuna Eklendi</option></select><select id="lineSize" aria-label="Sayfadaki replik sayısı"><option>25</option><option>50</option><option>100</option></select></div><div id="lineList" class="line-list"></div><div id="pager" class="pager"></div></section><footer class="vault-foot"><span>Revizyon <b>${esc(d.dataRevision||state.data.dataRevision||'—')}</b></span><span>Son senkron <b>${date(d.generatedAt||state.data.generatedAt)}</b></span><span>Kaynak sekme <b>${esc(d.character||c.name)}</b></span></footer></div>`;$('#lineSearch').oninput=e=>{state.detail.q=e.target.value;state.detail.page=1;lines()};$('#lineStatus').onchange=e=>{state.detail.st=e.target.value;state.detail.page=1;lines()};$('#lineSize').onchange=e=>{state.detail.size=Number(e.target.value);state.detail.page=1;lines()};Dossier.mount($('#modalContent'));lines()}
function rowText(r){return Object.values(r).filter(v=>v!=null).join(' ').toLocaleLowerCase('tr-TR')}
function lineRows(){const q=state.detail.q.trim().toLocaleLowerCase('tr-TR');return(state.detail.d.rows||[]).filter(r=>{const st=String(r.status||''),ok=state.detail.st==='all'||st===state.detail.st||(state.detail.st==='Kayit Alindi'&&st==='Kayıt Alındı');return ok&&(!q||rowText(r).includes(q))})}
function rowCard(r){const rs=r.status==='Kayit Alindi'?'Kayıt Alındı':(r.status||'Durum Yok');return`<article class="line-card"><header><b>#${esc(r.order??'—')}</b><span data-s="${esc(r.status||'')}">${esc(rs)}</span><small>Satır seslendiren: <strong>${esc(r.voiceActor||'—')}</strong></small></header><div class="dialogues"><div><small>ENGLISH</small><p>${esc(r.english||'—')}</p></div><div><small>TÜRKÇE</small><p>${esc(r.turkish||'—')}</p></div></div><div class="technical"><div><small>WAV DOSYA ADI</small><code>${esc(r.wav||'—')}</code></div><div><small>WEM ID</small><code>${esc(r.wemId||'—')}</code></div><div><small>INTERNAL NAME</small><code>${esc(r.internalName||'—')}</code></div><div><small>TARİH</small><em>${esc(r.date?date(r.date):'—')}</em></div><div class="note"><small>NOT</small><em>${esc(r.note||'—')}</em></div></div></article>`}
function lines(){const a=lineRows(),n=state.detail.d.rows.length,pages=Math.max(1,Math.ceil(a.length/state.detail.size));state.detail.page=clamp(state.detail.page,1,pages);const start=(state.detail.page-1)*state.detail.size,shown=a.slice(start,start+state.detail.size);$('#lineCount').textContent=`${nf.format(a.length)} / ${nf.format(n)} satır`;$('#lineList').innerHTML=shown.length?shown.map(rowCard).join(''):'<div class="no-lines">Eşleşen satır bulunamadı.</div>';$('#pager').innerHTML=`<button id="prev" ${state.detail.page<=1?'disabled':''}>← Önceki</button><span><b>${state.detail.page}</b> / ${pages}<small>${shown.length?nf.format(start+1)+'–'+nf.format(start+shown.length):'0'} gösteriliyor</small></span><button id="next" ${state.detail.page>=pages?'disabled':''}>Sonraki →</button>`;$('#prev').onclick=()=>{state.detail.page--;lines();$('.all-lines').scrollIntoView({behavior:'smooth'})};$('#next').onclick=()=>{state.detail.page++;lines();$('.all-lines').scrollIntoView({behavior:'smooth'})}}
function controls(){ $('#searchInput').oninput=e=>{state.search=e.target.value;characters()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;characters()};$('#filterTabs').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;$$('#filterTabs button').forEach(x=>x.classList.toggle('active',x===b));state.filter=b.dataset.filter;characters()};const m=$('#characterModal');$('#modalClose').onclick=()=>m.close();m.onclick=e=>{if(e.target===m)m.close()};m.onclose=()=>document.body.classList.remove('modal-open')}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(e=>io.observe(e))}
function tilt(){if(matchMedia('(pointer:coarse), (prefers-reduced-motion:reduce)').matches)return;$$('.tilt-card').forEach(c=>{if(c.dataset.tilt)return;c.dataset.tilt=1;c.onmousemove=e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(900px) rotateX(${-y*2.5}deg) rotateY(${x*2.5}deg) translateY(-2px)`};c.onmouseleave=()=>c.style.transform=''})}
function cosmos(){const c=$('#cosmos'),x=c.getContext('2d'),red=matchMedia('(prefers-reduced-motion:reduce)').matches;let w,h,stars=[];function size(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);c.width=w*d;c.height=h*d;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.min(140,Math.max(55,Math.floor(w*h/12000)))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.2+.2,s:Math.random()*.17+.03,a:Math.random()*.65+.2}))}function draw(){x.clearRect(0,0,w,h);stars.forEach(p=>{p.y-=p.s;if(p.y<0)p.y=h;x.fillStyle=`rgba(210,195,255,${p.a})`;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()});if(!red)requestAnimationFrame(draw)}size();addEventListener('resize',size);draw()}

window.getDossierDetail=()=>state.detail;
enhancePage();controls();reveal();tilt();load();setInterval(()=>load(true).catch(()=>setSync('error')),60000);