/* ODIUM Marvel Rivals — hero art + responsive card stack v6.2 */
(()=>{
const VER='6.2';
const TITLES={
'Adam Warlock':'Hero Card Adam Warlock','Angela':'Angela Hero Card','Black Cat':'Hero Card Black Cat','Black Panther':'Hero Card Black Panther','Black Widow':'Hero Card Black Widow','Blade':'Blade Hero Card','Hulk':'Hulk Hero Card','Capt. America':'Hero Card Captain America','Cloak':'Hero Card Cloak & Dagger','Dagger':'Hero Card Cloak & Dagger','Cyclops':'Hero Card Cyclops','Dare Devil':'Daredevil Hero Card','Deadpool':'Hero Card Deadpool','Devil Dinosaur':'Hero Card Devil Dinosaur','Dr.Strange':'Hero Card Doctor Strange','Elsa Bloodstone':'Hero Card Elsa Bloodstone','Emma Frost':'Hero Card Emma Frost','Gambit':'Gambit Hero Card','Groot':'Hero Card Groot','Hawkeye':'Hero Card Hawkeye','Hela':'Hela Prestige Artwork','Human Torch':'Hero Card Human Torch','Invisible Woman':'Hero Card Invisible Woman','Iron Fist':'Prestigeironfist','Iron Man':'Iron man prestige','Jeff':'Hero Card Jeff','Loki':'Hero Card Loki','Luna Snow':'Hero Card Luna Snow','Magik':'Magik marvel rivals prestige art','Magneto':'Magneto prestige','Mantis':'Hero Card Mantis','Mr.Fantastic':'Hero Card Mister Fantastic','Moon Knight':'Moonknight prestige','Namor':'Namor prestige','Peni Parker':'Peni Parker Prestige Artwork','Phoenix':'Phoenix prestige','Psylocke':'Hero Card Psylocke','Rocket Raccoon':'Hero Card Rocket Raccoon','Rogue':'Rogue Hero Card','Scarlet Witch':'Hero Card Scarlet Witch','Spider-Man':'Hero Card Spider-Man','Squirrel Girl':'Prestige squirellgirl','Star Lord':'Hero Card Star-Lord','Storm':'Hero Card Storm','The Punisher':'Punisher prestige','The Thing':'The Thing Prestige art','Thor':'Hero Card Thor','Ultron':'Ultron Prestige art','Venom':'Hero Card Venom','White Fox':'Hero Card White Fox','Winter Soldier':'Winter soldier prestige','Wolverine':'Hero Card Wolverine','Galacta':'Galacta'};
const API_SLUG={'Capt. America':'captain-america','Dr.Strange':'doctor-strange','Mr.Fantastic':'mister-fantastic','Dare Devil':'daredevil','Jeff':'jeff-the-land-shark','Star Lord':'star-lord','Cloak':'cloak-and-dagger','Dagger':'cloak-and-dagger'};
const slug=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const cache=new Map();
const raw=n=>`https://raw.githubusercontent.com/thedrowned925/marvelrivalsodium/main/assets/characters/${slug(n)}.webp`;
const fandom=(title,ext)=>`https://marvelrivals.fandom.com/wiki/Special:Redirect/file/${encodeURIComponent(title+'.'+ext)}`;
const proxy=u=>`https://images.weserv.nl/?url=${encodeURIComponent(u)}&w=900&h=1300&fit=cover&output=webp&q=88`;
const apiIcon=n=>`https://marvelrivalsapi.com/rivals/heroes/${API_SLUG[n]||slug(n)}/icon.png`;
function candidates(name){const title=TITLES[name]||('Hero Card '+name);return [raw(name),proxy(fandom(title,'png')),proxy(fandom(title,'jpg')),proxy(fandom(title,'webp')),fandom(title,'png'),fandom(title,'jpg'),apiIcon(name)];}
function apply(img,name,done){const list=candidates(name);let i=0;const next=()=>{if(i>=list.length){img.dataset.failed='true';done&&done(false);return;}const url=list[i++];img.onload=()=>{if(img.naturalWidth<64||img.naturalHeight<64){next();return;}cache.set(name,url);img.dataset.failed='false';img.dataset.source=url.includes('raw.githubusercontent')?'github-cache':url.includes('weserv')?'fandom-proxy':url.includes('fandom.com')?'fandom-direct':'api-fallback';done&&done(true);};img.onerror=next;img.src=url;};const cached=cache.get(name);if(cached){img.onload=()=>done&&done(true);img.onerror=next;img.src=cached;}else next();}
function cardName(card){return card?.dataset?.name||card?.querySelector('.char-name')?.textContent?.trim()||'';}
function stack(card){if(!card||card.querySelector(':scope > .mr-card-ui'))return;const selectors=['.char-meta','.char-mini','.char-progress-row','.char-bar','.char-head'];const parts=selectors.map(s=>card.querySelector(':scope > '+s)).filter(Boolean);if(!parts.length)return;const ui=document.createElement('div');ui.className='mr-card-ui';parts.forEach(el=>ui.appendChild(el));card.appendChild(ui);}
function decorate(card){if(!card)return;stack(card);if(card.dataset.artV6===VER)return;const name=cardName(card);if(!name)return;card.dataset.artV6=VER;card.querySelectorAll(':scope > .mr-hero-art').forEach(n=>n.remove());const img=document.createElement('img');img.className='mr-hero-art';img.alt='';img.loading='lazy';img.decoding='async';card.prepend(img);apply(img,name,ok=>card.dataset.artState=ok?img.dataset.source:'missing');}
function decorateCards(){document.querySelectorAll('#characterGrid .char-card').forEach(decorate);}
function decorateVault(){const root=document.querySelector('#modalContent');if(!root)return;const h=root.querySelector('.vault-head');if(!h||h.dataset.artV6===VER)return;const name=h.querySelector('h3')?.textContent?.trim();if(!name)return;h.dataset.artV6=VER;h.querySelectorAll('.mr-vault-art').forEach(n=>n.remove());const img=document.createElement('img');img.className='mr-vault-art';img.alt='';img.decoding='async';h.appendChild(img);apply(img,name);}
function boot(){decorateCards();decorateVault();const grid=document.querySelector('#characterGrid');const modal=document.querySelector('#modalContent');if(grid)new MutationObserver(()=>requestAnimationFrame(decorateCards)).observe(grid,{childList:true,subtree:true});if(modal)new MutationObserver(()=>requestAnimationFrame(decorateVault)).observe(modal,{childList:true,subtree:true});setTimeout(decorateCards,250);setTimeout(decorateCards,900);setTimeout(decorateCards,1800);}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();
