const assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),path=require('node:path');
const bundled=require('esbuild').buildSync({entryPoints:[path.join(__dirname,'../supabase/functions/rivals-audio-admin/video.ts')],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
const moduleUnderTest=new Module(__filename);moduleUnderTest._compile(bundled,__filename);const {inspectVideo,videoAction}=moduleUnderTest.exports;
const fixture=fs.readFileSync(path.join(__dirname,'fixtures/video-1080.mp4'));
assert.deepEqual(inspectVideo(fixture),{width:1920,height:1080,duration:1});
assert.throws(()=>inspectVideo(fixture.subarray(0,40)));
const wrong=Buffer.from(fixture),avc=wrong.indexOf('avc1',wrong.indexOf('stsd'));wrong.writeUInt16BE(1280,avc+28);assert.throws(()=>inspectVideo(wrong),/1920/);
const codec=Buffer.from(fixture);codec.write('hvc1',avc);assert.throws(()=>inspectVideo(codec),/H.264/);
const longer=Buffer.from(fixture),mvhd=longer.indexOf('mvhd');longer.writeUInt32BE(91000,mvhd+20);assert.throws(()=>inspectVideo(longer),/90/);
let failFinish=true,lock=false,conflict=true,ref='a'.repeat(40),commits=0,removed=0;const treeBases=[];
const tables={rivals_video_uploads:[],rivals_character_videos:[]};
function query(table){let action='select',values,filters=[];const b={select(){return b},insert(v){action='insert';values=v;return b},update(v){action='update';values=v;return b},eq(k,v){filters.push(r=>r[k]===v);return b},neq(k,v){filters.push(r=>r[k]!==v);return b},in(k,v){filters.push(r=>v.includes(r[k]));return b},maybeSingle(){return Promise.resolve(run(true))},then(y,n){return Promise.resolve(run(false)).then(y,n)}};function run(single){if(action==='insert'){tables[table].push({status:'uploading',...values});return{data:null}}const rows=tables[table].filter(r=>filters.every(f=>f(r)));if(action==='update')rows.forEach(r=>Object.assign(r,values));return{data:single?(rows[0]?{...rows[0]}:null):rows.map(r=>({...r}))}}return b}
const admin={from:query,rpc:async(name,args)=>{if(name==='rivals_github_token')return{data:'mock-private-key'};if(name==='rivals_acquire_lock'){assert(!lock);lock=true;return{data:true}}if(name==='rivals_release_lock'){lock=false;return{data:null}}if(name==='rivals_finish_video'){if(failFinish){failFinish=false;return{error:'temporary database failure'}}const j=tables.rivals_video_uploads.find(j=>j.id===args.job);assert.equal(j.status,'github_saved');tables.rivals_character_videos.push({character:j.character,video_url:args.url,duration:args.seconds});j.status='published';return{data:null}}throw Error(name)},storage:{from:()=>({createSignedUploadUrl:async()=>({data:{token:'upload-only'}}),download:async()=>({data:new Blob([fixture])}),remove:async()=>{removed++;return{data:null}}})}};
global.fetch=async(url,opts)=>{const p=new URL(url).pathname.replace('/repos/thedrowned925/marvelrivalsodium',''),body=opts.body&&JSON.parse(opts.body);let data={};if(p==='/git/blobs'){assert(body.content);data={sha:'b'.repeat(40)}}else if(p==='/git/ref/heads/main')data={object:{sha:ref}};else if(p.startsWith('/git/commits/'))data={tree:{sha:ref==='a'.repeat(40)?'initial-tree':'workbook-tree'}};else if(p==='/git/trees'){treeBases.push(body.base_tree);assert(body.tree.some(x=>x.path.endsWith('.mp4')));data={sha:'c'.repeat(40)}}else if(p==='/git/commits'){commits++;assert.equal(body.parents[0],ref);data={sha:String(commits).repeat(40)}}else if(p==='/git/refs/heads/main'){assert.equal(body.force,false);if(conflict){conflict=false;ref='d'.repeat(40);return new Response('{}',{status:422})}ref=body.sha}else throw Error(p);return new Response(JSON.stringify(data),{status:200})};
(async()=>{const owner={user_id:'test-owner'},roster={'black-panther':'Black Panther'};const ticket=await videoAction('video_prepare',{character:'black-panther',size:fixture.length},owner,admin,roster,'');assert.equal(ticket.token,'upload-only');await assert.rejects(videoAction('video_publish',{id:ticket.id},{user_id:'intruder'},admin,roster,''),/bulunamadı/);
await assert.rejects(videoAction('video_publish',{id:ticket.id},owner,admin,roster,''),/onayı bekliyor/);assert.deepEqual(treeBases,['initial-tree','workbook-tree']);assert.equal(tables.rivals_character_videos.length,0);assert.equal(removed,0);assert.equal(lock,false);
await videoAction('video_publish',{id:ticket.id},owner,admin,roster,'');assert.equal(commits,2);assert.equal(removed,1);assert(tables.rivals_character_videos[0].video_url.includes('/'+ref+'/assets/video/managed/'));await videoAction('video_publish',{id:ticket.id},owner,admin,roster,'');assert.equal(commits,2);
console.log('PASS: real 1080p MP4 validation, invalid codec/size/duration, owner scoping, concurrent workbook commit preservation, pending-publication retry and idempotency.');})().catch(e=>{console.error(e);process.exitCode=1});
