(()=>{
 const cfg=window.ODIUM_ADMIN_CONFIG,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
 const client=OdiumSupabase.createClient(cfg.url,cfg.key,{auth:{storage:sessionStorage,storageKey:'odium-admin-session',persistSession:true,detectSessionInUrl:false}});
 let roster=[],state=null,selected='',busy=false;const objectURLs=new Map();
 const legacy={blade:{hover:'hover/intikam.wav',detail:'detail/BİN kesik ulti.wav'},groot:{hover:'hover/Groot_ulti1_ADIM_GROOOOT.wav',detail:'detail/Groot_ulti2_Adimiz_Groot.wav'},'iron-fist':{hover:'hover/IronFist_ulti2_skin_GongXiFaCai.wav',detail:'detail/IronFist_ulti1_Ejderhayi_Saldik.wav'},'spider-man':{hover:'hover/SpiderMan_ulti2_OrumcekAdama_Bulasmayin.wav',detail:'detail/SpiderMan_ulti1_HerkeseBendenAg.wav'},'the-punisher':{hover:'hover/Punisher_ulti1_Cellat.wav',detail:'detail/Punisher_ulti2_Kendi_Yontemlerimle.wav'}};
 function message(text,error=false,auth=false){const el=$(auth?'#authMessage':'#message');el.textContent=text;el.hidden=!text;el.dataset.error=String(error)}
 function clearFiles(){for(const url of objectURLs.values())URL.revokeObjectURL(url);objectURLs.clear();for(const kind of ['hover','detail']){$(`[name=${kind}]`).value='';$(`[data-filename=${kind}]`).textContent='Yeni dosya seçilmedi';const audio=$(`[data-preview=${kind}]`);audio.pause();audio.removeAttribute('src');audio.hidden=true}}
 async function call(action,body={},anonymous=false){
  const session=anonymous?null:(await client.auth.getSession()).data.session;
  const multipart=body instanceof FormData;
  const r=await fetch(cfg.url+'/functions/v1/'+cfg.functionName+'?action='+encodeURIComponent(action),{method:'POST',headers:{apikey:cfg.key,...(session?{Authorization:'Bearer '+session.access_token}:{}),...(!multipart?{'Content-Type':'application/json'}:{})},body:multipart?body:JSON.stringify(body),signal:AbortSignal.timeout(180000)});
  const result=await r.json().catch(()=>({error:'Sunucuya ulaşılamadı.'}));if(!r.ok)throw new Error(result.error||'İşlem tamamlanamadı.');return result;
 }
 function lock(value){busy=value;$$('form button,#roster button,#settingsToggle,#logout,input[type=file]').forEach(b=>b.disabled=value)}
 function displayName(c){return window.HERO_DESIGN?.[c.name]?.name||c.name}
 function list(){const q=$('#characterSearch').value.toLocaleLowerCase('tr');const choices=roster.filter(c=>(c.name+' '+displayName(c)).toLocaleLowerCase('tr').includes(q));$('#rosterCount').textContent=choices.length+' karakter';$('#roster').replaceChildren(...choices.map(c=>{const b=document.createElement('button');b.type='button';b.classList.toggle('active',c.slug===selected);b.textContent=displayName(c);const t=state?.tracks.find(t=>t.character===c.slug),n=Number(!!(t?.hover_url||legacy[c.slug]?.hover))+Number(!!(t?.detail_url||legacy[c.slug]?.detail));const small=document.createElement('small');small.textContent=n+'/2 ses';b.append(small);b.disabled=busy;b.onclick=()=>select(c.slug);return b}))}
 function current(){const c=roster.find(c=>c.slug===selected);if(!c)return;const p=window.HERO_DESIGN?.[c.name];$('#heroName').textContent=displayName(c);$('#heroSubtitle').textContent=c.voiceActor?'Türkçe sesi: '+c.voiceActor:'Seslendirmen henüz atanmadı';$('.selected-hero').style.setProperty('--hero-color',p?.color||'#5c6380');const img=$('#heroPortrait');img.hidden=!p?.portrait;img.onerror=()=>img.hidden=true;if(p?.portrait)img.src='../'+p.portrait;
  const track=state?.tracks.find(t=>t.character===selected);for(const kind of ['hover','detail']){const url=track?.[kind+'_url']||(legacy[selected]?.[kind]?new URL('../assets/audio/'+legacy[selected][kind],document.baseURI).href:null),audio=$(`[data-current=${kind}]`);audio.pause();audio.hidden=!url;$(`[data-empty=${kind}]`).hidden=!!url;if(url)audio.src=url;else audio.removeAttribute('src')}
 }
 function select(slug){if(busy)return;selected=slug;$('#publishForm [name=character]').value=slug;clearFiles();current();list()}
 function jobs(){const root=$('#pendingJobs');root.replaceChildren();for(const job of state.jobs){if(!job.commit_sha||!['github_saved','publishing'].includes(job.status))continue;const b=document.createElement('button');b.textContent=job.character+' · Bekleyen yayını tamamla';b.onclick=async()=>{lock(true);try{await call('retry',{job:job.id});message('Sesler yayına alındı.');await refresh()}catch(e){message(e.message,true)}finally{lock(false)}};root.append(b)}}
 async function refresh(){state=await call('status');$('#adminName').textContent=state.username;$('#githubState').textContent=state.githubConnected?'GitHub bağlantısı kayıtlı.':'Ses yayımlamak için GitHub bağlantısını tamamla.';$('#accountForm [name=username]').value=state.username;$('#settings').hidden=state.githubConnected;list();current();jobs()}
 async function enter(){await refresh();$('#auth').hidden=true;$('#dashboard').hidden=false;$('#logout').hidden=false;if(!selected)select(roster[0]?.slug||'')}
 const setupCode=new URLSearchParams(location.hash.slice(1)).get('setup');if(setupCode){$('#loginForm').hidden=true;$('#setupForm').hidden=false;$('#setupForm [name=code]').value=setupCode;history.replaceState(null,'',location.pathname)}
 $('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;lock(true);message('Giriş yapılıyor…',false,true);try{const data=await call('login',Object.fromEntries(new FormData(form)),true);const result=await client.auth.setSession(data);if(result.error)throw result.error;form.elements.namedItem('password').value='';await enter();message('',false,true)}catch(error){message(error.message,true,true)}finally{lock(false)}};
 $('#setupForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;lock(true);try{await call('bootstrap',Object.fromEntries(new FormData(form)),true);form.reset();form.hidden=true;$('#loginForm').hidden=false;message('Hesabın oluşturuldu. Kullanıcı adın ve şifrenle giriş yap.',false,true)}catch(error){message(error.message,true,true)}finally{lock(false)}};
 $('#logout').onclick=async()=>{await client.auth.signOut();state=null;clearFiles();$$('audio').forEach(a=>a.pause());$('#dashboard').hidden=true;$('#auth').hidden=false;$('#logout').hidden=true;$('#loginForm').hidden=false;$('#setupForm').hidden=true;message('Çıkış yapıldı.',false,true)};
 $('#settingsToggle').onclick=()=>$('#settings').hidden=!$('#settings').hidden;$('#characterSearch').oninput=list;
 for(const kind of ['hover','detail'])$(`[name=${kind}]`).onchange=e=>{const file=e.target.files[0],audio=$(`[data-preview=${kind}]`);if(objectURLs.has(kind)){URL.revokeObjectURL(objectURLs.get(kind));objectURLs.delete(kind)}audio.pause();audio.removeAttribute('src');audio.hidden=true;if(!file)return;if(file.size>10*1024*1024||!file.size||!(/\.(wav|mp3|ogg)$/i.test(file.name))){message('WAV, MP3 veya OGG seç; her dosya en fazla 10 MB olabilir.',true);e.target.value='';return}const url=URL.createObjectURL(file);objectURLs.set(kind,url);audio.src=url;audio.hidden=false;$(`[data-filename=${kind}]`).textContent=file.name+' · '+(file.size/1024/1024).toFixed(2)+' MB';message('')};
 $('#publishForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const body=new FormData(e.currentTarget);if(!['hover','detail'].some(k=>body.get(k)?.size)){message('Önce en az bir ses dosyası seç.',true);return}body.set('job',crypto.randomUUID());lock(true);message('Sesler yükleniyor, GitHub’a kaydediliyor ve yayına alınıyor…');try{const result=await call('publish',body);clearFiles();await refresh();message('Yayımlandı. Açık ziyaretçi sayfaları yeni sesleri otomatik alır.');$('#lastPublish').replaceChildren(document.createTextNode('Son yayın tamamlandı.'));if(/^[a-f0-9]{40}$/.test(result.commit)){const a=document.createElement('a');a.href='https://github.com/thedrowned925/marvelrivalsodium/commit/'+result.commit;a.target='_blank';a.rel='noopener';a.textContent='GitHub kaydı ↗';$('#lastPublish').append(a)}}catch(error){message(error.message,true);await refresh().catch(()=>{})}finally{lock(false)}};
 $('#githubForm').onsubmit=async e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('token');lock(true);try{await call('github',{token:input.value});await refresh();message('GitHub yazma yetkisi doğrulandı ve anahtar şifreli kaydedildi.')}catch(error){message(error.message,true)}finally{input.value='';lock(false)}};
 $('#accountForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;lock(true);try{await call('account',Object.fromEntries(new FormData(form)));form.elements.namedItem('password').value='';await refresh();message('Giriş bilgilerin güncellendi.')}catch(error){message(error.message,true)}finally{lock(false)}};
 window.addEventListener('pagehide',()=>{for(const url of objectURLs.values())URL.revokeObjectURL(url)});
 (async()=>{try{const r=await fetch('../data/data.json');if(!r.ok)throw Error('Karakterler yüklenemedi.');roster=(await r.json()).characters;const session=(await client.auth.getSession()).data.session;if(session&&!setupCode)await enter()}catch(error){message(error.message,true,true)}})();
})();
